'use client';
import { useEffect, useMemo, useState } from 'react';
import { AppState, loadState, replyStatus, isMeetingCancelled, toggleMeetingCancel } from '@/lib/store';
import { getSession, Session } from '@/lib/session';
import Link from 'next/link';
function ic(t?:string){return t==='registered'?'✅':t==='declined'?'❌':t==='interested'?'❤️':''}
const weekdays=['日','一','二','三','四','五','六'];
function ymd(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monthKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function addMonths(d:Date,n:number){const x=new Date(d);x.setMonth(x.getMonth()+n);return x}
export default function Calendar(){
  const [s,setS]=useState<AppState|null>(null);const [session,setSessionState]=useState<Session|null>(null);const [child,setChild]=useState('all');const [view,setView]=useState<'month'|'list'>('month');const [base,setBase]=useState(new Date());
  useEffect(()=>{setS(loadState());setSessionState(getSession())},[]);
  if(!s)return <div className="card">載入中...</div>;
  if(!session)return <section className="hero"><span className="badge red">需要登入旅團</span><h1>行事曆需要先登入</h1><p>未登入前不顯示旅團內部行事曆、活動及圖書館。請先選擇旅團並登入。</p><Link className="btn primary" href="/login">前往登入</Link></section>;
  const role=session.role; const canCancel=['super_admin','admin','group_leader','branch_leader'].includes(role);
  const parent=role==='parent'?s.users.find(u=>u.id===session.userId):s.users.find(u=>u.role==='parent');
  const children=s.members.filter(m=>(parent?.childMemberIds||[]).includes(m.id)||m.parentUserId===parent?.id);
  function cancelDay(branchId:string,date:string){ toggleMeetingCancel(branchId,date,session.userId,'領袖標記不用集會'); setS(loadState()); }
  function visibleEvent(e:any){ if(role==='member'){const m=s.members.find(x=>x.id===session.memberId);return !!m&&e.targetMemberIds.includes(m.id)&&replyStatus(s,e.id,m.id)?.type!=='declined'} if(role==='parent'){return children.some(c=>e.targetMemberIds.includes(c.id))} return true; }
  function rightForEvent(e:any){ if(['admin','super_admin','group_leader','branch_leader','coach'].includes(role)){const targets=s.members.filter(m=>e.targetMemberIds.includes(m.id));const counts:any={registered:0,interested:0,declined:0,unresponded:0};targets.forEach(m=>{const r=replyStatus(s,e.id,m.id);counts[r?.type||'unresponded']++});return `✅${counts.registered} ❤️${counts.interested} ⚠️${counts.unresponded}`;} if(role==='parent'){const cs=(child==='all'?children:children.filter(c=>c.id===child)).filter(c=>e.targetMemberIds.includes(c.id));return cs.map(c=>`${child==='all'?c.name:''}${ic(replyStatus(s,e.id,c.id)?.type)||'·'}`).join(' ')||'—'} if(role==='member'){const r=replyStatus(s,e.id,session.memberId||'');return `${ic(r?.type)} ${r?.type==='interested'?'等待家長確認':''}`} return '' }
  const calendarItems=useMemo(()=>{
    const items:any[]=[];
    s.events.filter(e=>e.status==='published').filter(visibleEvent).forEach(e=>items.push({type:'event',date:e.date,title:e.title,purple:e.kind==='notice_troop_participation',event:e}));
    s.regularMeetings.filter(r=>r.enabled).forEach(r=>{for(let i=0;i<90;i++){const d=new Date();d.setDate(d.getDate()+i);const date=ymd(d);if(d.getDay()!==r.weekday)continue;const cancelled=isMeetingCancelled(s,r.branchId,date);if(cancelled&&role==='member')continue;items.push({type:'meeting',date,title:r.title,purple:false,cancelled,meeting:r});}});
    return items;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[s,role,child,session?.memberId]);
  const first=new Date(base.getFullYear(),base.getMonth(),1);const start=new Date(first);start.setDate(1-first.getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});
  return <div className="stack"><section className="hero"><span className="badge gold">📅 行事曆</span><h1>{role==='member'?'我的行事曆':role==='parent'?'子女行事曆':'領袖行事曆'}</h1><p>以月曆為主、清單為輔。領袖可在日常集會按 × 標記不用集會；成員不會看到已取消的集會。</p><div className="row"><button className={`btn ${view==='month'?'primary':''}`} onClick={()=>setView('month')}>月曆</button><button className={`btn ${view==='list'?'primary':''}`} onClick={()=>setView('list')}>清單</button></div></section>{role==='parent'&&<section className="card row"><strong>子女：</strong><button className={`btn ${child==='all'?'primary':''}`} onClick={()=>setChild('all')}>全部</button>{children.map(c=><button key={c.id} className={`btn ${child===c.id?'primary':''}`} onClick={()=>setChild(c.id)}>{c.name}</button>)}</section>}
  {view==='month'?<section className="card stack"><div className="row" style={{justifyContent:'space-between'}}><button className="btn" onClick={()=>setBase(addMonths(base,-1))}>← 上月</button><h2>{monthKey(base)}</h2><button className="btn" onClick={()=>setBase(addMonths(base,1))}>下月 →</button></div><div className="month-grid">{weekdays.map(w=><div className="month-head" key={w}>星期{w}</div>)}{days.map(d=>{const date=ymd(d);const its=calendarItems.filter(i=>i.date===date);return <div key={date} className={`month-cell ${d.getMonth()!==base.getMonth()?'dim':''}`}><div className="day-num">{d.getDate()}</div>{its.slice(0,4).map((it,idx)=><div key={idx} className={`mini-event ${it.purple?'purple':''} ${it.cancelled?'cancelled':''}`}>{it.type==='meeting'?'🔵':'🟣'} {it.title}{it.type==='meeting'&&canCancel&&<button style={{float:'right',border:0,background:'transparent',cursor:'pointer'}} onClick={()=>cancelDay(it.meeting.branchId,it.date)}>{it.cancelled?'↺':'×'}</button>}</div>)}</div>})}</div></section>:<section className="card stack"><h2>清單</h2>{calendarItems.sort((a,b)=>a.date.localeCompare(b.date)).slice(0,60).map((it,idx)=><div key={idx} className={`event-line ${it.purple?'event-purple':'event-blue'}`}><div><strong>{it.cancelled?'已取消：':''}{it.type==='meeting'?'🔵':'🟣'} {it.title}</strong><div className="muted">{it.date}{it.type==='event'?` · ${it.event.location} · ${it.event.source}`:` · ${it.meeting.startTime}-${it.meeting.endTime} · ${it.meeting.location}`}</div></div><div className="row">{it.type==='event'?<span>{rightForEvent(it.event)}</span>:<span className={`badge ${it.cancelled?'red':'green'}`}>{it.cancelled?'不用集會':'恆常'}</span>}{it.type==='meeting'&&canCancel&&<button className="btn" onClick={()=>cancelDay(it.meeting.branchId,it.date)}>{it.cancelled?'恢復':'× 標記不用集會'}</button>}{it.type==='event'&&['admin','super_admin','group_leader','branch_leader','coach'].includes(role)&&<a className="btn" href={`/admin/registrations?eventId=${it.event.id}`}>查看→</a>}</div></div>)}</section>}
  </div>
}
